#!/usr/bin/env python

import os, urlparse, sys

if len(sys.argv[1:]) < 1:
    print >>sys.stderr, 'Usage: ssh-uri [flags] <uri>'
    sys.exit(1)

uristr = sys.argv[-1]
flags = sys.argv[1:-1]

if not uristr.startswith('ssh://'):
    print >>sys.stderr, 'Error: %r is not an SSH URI' % (uristr,)
    print >>sys.stderr, 'Usage: ssh-uri [flags] <uri>'
    sys.exit(1)
u = urlparse.urlparse(uristr)

args = ['ssh'] + flags
if u.port is not None:
    args.extend(('-p', str(u.port)))
where = u.hostname
if u.username is not None:
    where = u.username + '@' + where
args.append(where)

os.execvp('ssh', args)
